// Generated by gencpp from file move/NewGoal.msg
// DO NOT EDIT!


#ifndef MOVE_MESSAGE_NEWGOAL_H
#define MOVE_MESSAGE_NEWGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move
{
template <class ContainerAllocator>
struct NewGoal_
{
  typedef NewGoal_<ContainerAllocator> Type;

  NewGoal_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , cmd()  {
    }
  NewGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , cmd(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::move::NewGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move::NewGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NewGoal_

typedef ::move::NewGoal_<std::allocator<void> > NewGoal;

typedef boost::shared_ptr< ::move::NewGoal > NewGoalPtr;
typedef boost::shared_ptr< ::move::NewGoal const> NewGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move::NewGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move::NewGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move::NewGoal_<ContainerAllocator1> & lhs, const ::move::NewGoal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move::NewGoal_<ContainerAllocator1> & lhs, const ::move::NewGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move::NewGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move::NewGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::NewGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::NewGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::NewGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::NewGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f12a1beafbdce7c5cf13573ff19d07b9";
  }

  static const char* value(const ::move::NewGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf12a1beafbdce7c5ULL;
  static const uint64_t static_value2 = 0xcf13573ff19d07b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::move::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move/NewGoal";
  }

  static const char* value(const ::move::NewGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move::NewGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"string cmd\n"
;
  }

  static const char* value(const ::move::NewGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move::NewGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move::NewGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move::NewGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_MESSAGE_NEWGOAL_H
